"""initial_schema

Revision ID: 859ba5a2e55b
Revises: 
Create Date: 2026-09-28 21:30:20.967783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '859ba5a2e55b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_place_id', sa.String(length=512), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('formatted_address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('primary_type', sa.String(length=128), nullable=True),
    sa.Column('types_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('website_uri', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('opening_hours_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('photo_refs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_places_provider', 'places', ['provider'], unique=False)
    op.create_index('ix_places_provider_place_id', 'places', ['provider_place_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('raw_intent', sa.Text(), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_text', sa.Text(), nullable=True),
    sa.Column('destination_text', sa.Text(), nullable=True),
    sa.Column('travel_mode', sa.String(length=32), nullable=True),
    sa.Column('constraints_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activities_status', 'activities', ['status'], unique=False)
    op.create_index('ix_activities_user_id', 'activities', ['user_id'], unique=False)
    op.create_table('plan_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=256), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plan_runs_activity_id', 'plan_runs', ['activity_id'], unique=False)
    op.create_index(op.f('ix_plan_runs_idempotency_key'), 'plan_runs', ['idempotency_key'], unique=True)
    op.create_index('ix_plan_runs_status', 'plan_runs', ['status'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_from_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plans_activity_id', 'plans', ['activity_id'], unique=False)
    op.create_index('ix_plans_status', 'plans', ['status'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_run_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim', sa.Text(), nullable=True),
    sa.Column('relevance', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_run_id'], ['plan_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_plan_run_id', 'evidence', ['plan_run_id'], unique=False)
    op.create_index('ix_evidence_source_type', 'evidence', ['source_type'], unique=False)
    op.create_table('packing_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('item', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_packing_items_plan_id', 'packing_items', ['plan_id'], unique=False)
    op.create_table('plan_places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'place_id', name='uq_plan_place')
    )
    op.create_index('ix_plan_places_place_id', 'plan_places', ['place_id'], unique=False)
    op.create_index('ix_plan_places_plan_id', 'plan_places', ['plan_id'], unique=False)
    op.create_table('plan_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('section_type', sa.String(length=64), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'order_index', name='uq_plan_section_order')
    )
    op.create_index('ix_plan_sections_plan_id', 'plan_sections', ['plan_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('travel_mode', sa.String(length=32), nullable=True),
    sa.Column('origin_text', sa.Text(), nullable=True),
    sa.Column('destination_text', sa.Text(), nullable=True),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('polyline', sa.Text(), nullable=True),
    sa.Column('route_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routes_plan_id', 'routes', ['plan_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_run_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('response_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['plan_run_id'], ['plan_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_calls_plan_run_id', 'tool_calls', ['plan_run_id'], unique=False)
    op.create_index('ix_tool_calls_status', 'tool_calls', ['status'], unique=False)
    op.create_index('ix_tool_calls_tool_name', 'tool_calls', ['tool_name'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('detour_minutes', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('arrival_estimate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'order_index', name='uq_route_stop_order')
    )
    op.create_index('ix_route_stops_place_id', 'route_stops', ['place_id'], unique=False)
    op.create_index('ix_route_stops_route_id', 'route_stops', ['route_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_section_id', sa.UUID(), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_section_id'], ['plan_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_parent_task_id', 'tasks', ['parent_task_id'], unique=False)
    op.create_index('ix_tasks_plan_section_id', 'tasks', ['plan_section_id'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('itinerary_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_itinerary_items_plan_id', 'itinerary_items', ['plan_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('task_id != depends_on_id', name='ck_no_self_dependency'),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_id', name='uq_task_dependency_pair')
    )
    op.create_index('ix_task_dependencies_depends_on_id', 'task_dependencies', ['depends_on_id'], unique=False)
    op.create_index('ix_task_dependencies_task_id', 'task_dependencies', ['task_id'], unique=False)

    # --- Circular FK resolution (Plan <-> PlanRun) ---
    # Both tables exist at this point. Add the two cross-referencing FKs
    # via ALTER TABLE to avoid a circular dependency at DDL time.
    op.create_foreign_key(
        'fk_plans_created_from_run_id',
        'plans',
        'plan_runs',
        ['created_from_run_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_plan_runs_plan_id',
        'plan_runs',
        'plans',
        ['plan_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_dependencies_task_id', table_name='task_dependencies')
    op.drop_index('ix_task_dependencies_depends_on_id', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index('ix_itinerary_items_plan_id', table_name='itinerary_items')
    op.drop_table('itinerary_items')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_plan_section_id', table_name='tasks')
    op.drop_index('ix_tasks_parent_task_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_route_stops_route_id', table_name='route_stops')
    op.drop_index('ix_route_stops_place_id', table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index('ix_tool_calls_tool_name', table_name='tool_calls')
    op.drop_index('ix_tool_calls_status', table_name='tool_calls')
    op.drop_index('ix_tool_calls_plan_run_id', table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index('ix_routes_plan_id', table_name='routes')
    op.drop_table('routes')
    op.drop_index('ix_plan_sections_plan_id', table_name='plan_sections')
    op.drop_table('plan_sections')
    op.drop_index('ix_plan_places_plan_id', table_name='plan_places')
    op.drop_index('ix_plan_places_place_id', table_name='plan_places')
    op.drop_table('plan_places')
    op.drop_index('ix_packing_items_plan_id', table_name='packing_items')
    op.drop_table('packing_items')
    op.drop_index('ix_evidence_source_type', table_name='evidence')
    op.drop_index('ix_evidence_plan_run_id', table_name='evidence')
    op.drop_table('evidence')
    # Drop circular FKs before dropping tables
    op.drop_constraint('fk_plan_runs_plan_id', 'plan_runs', type_='foreignkey')
    op.drop_constraint('fk_plans_created_from_run_id', 'plans', type_='foreignkey')
    op.drop_index('ix_plans_status', table_name='plans')
    op.drop_index('ix_plans_activity_id', table_name='plans')
    op.drop_table('plans')
    op.drop_index('ix_plan_runs_status', table_name='plan_runs')
    op.drop_index(op.f('ix_plan_runs_idempotency_key'), table_name='plan_runs')
    op.drop_index('ix_plan_runs_activity_id', table_name='plan_runs')
    op.drop_table('plan_runs')
    op.drop_index('ix_activities_user_id', table_name='activities')
    op.drop_index('ix_activities_status', table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_places_provider_place_id', table_name='places')
    op.drop_index('ix_places_provider', table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
