import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useLifeOS } from '../context/LifeOSContext';
import {
  Compass,
  CheckCircle2,
  Clock,
  ShieldCheck,
  AlertCircle,
  ArrowRight,
  TrendingDown,
  Building,
  MapPin,
  Bot,
  Sliders,
  X,
  FileCheck,
  AlertTriangle,
  ExternalLink,
  ChevronRight,
} from 'lucide-react';
import { LifeOSButton } from '../components/ui/LifeOSButton';
import { LifeOSModal } from '../components/ui/LifeOSModal';
import { LifeOSBadge } from '../components/ui/LifeOSBadge';

export const PlanPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const {
    activeGoal,
    plan,
    approvePlan,
    rejectPlan,
    modifyPlan,
    showToast,
  } = useLifeOS();

  const [showModifyModal, setShowModifyModal] = useState(false);
  const [budgetCap, setBudgetCap] = useState('₹15,000');
  const [maxCommute, setMaxCommute] = useState('45 mins');
  const [feedbackText, setFeedbackText] = useState('');
  const [showRejectModal, setShowRejectModal] = useState(false);

  const handleApprove = () => {
    approvePlan(plan.id);
  };

  const handleRejectSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    rejectPlan(plan.id, feedbackText);
    setShowRejectModal(false);
  };

  const handleModifySubmit = (e: React.FormEvent) => {
    e.preventDefault();
    modifyPlan(plan.id, {
      tradeOffs: [
        `Option A (Modified budget ${budgetCap}): Recalculated under ${maxCommute} commute limit.`,
        ...plan.tradeOffs.slice(1),
      ],
    });
    setShowModifyModal(false);
  };

  const risksAndMitigations = [
    {
      risk: 'Hostel Allotment Overcapacity / Waitlist',
      severity: 'Medium',
      mitigation: 'Research Agent pre-screened Shivani PG & Scholar Accommodations in Indira Nagar as instant fallbacks.',
    },
    {
      risk: 'Income Certificate Verification Delay',
      severity: 'High',
      mitigation: 'Document Agent flagged edistrict UP expedited counter (processing time: 48h).',
    },
    {
      risk: 'Metro Disruption or Peak Crowds',
      severity: 'Low',
      mitigation: 'Maps Agent audited feeder e-rickshaw routes via Faizabad Road corridor (34 min).',
    },
  ];

  return (
    <div className="space-y-6 max-w-5xl mx-auto animate-fade-in">
      {/* Header and Status */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200">
        <div>
          <div className="flex items-center gap-2 mb-1.5">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">
              Goal Plan Review
            </span>
            <span>•</span>
            <span className="text-xs font-semibold text-[#1E60F2]">
              {activeGoal.title}
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-[#0B192C] tracking-tight">
            AI-Synthesized Relocation Plan
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 mt-0.5">
            Generated by Planning Agent • Audited by Verification Agent
          </p>
        </div>

        <div>
          {plan.status === 'approved' ? (
            <LifeOSBadge variant="success" pulse>
              Approved by User
            </LifeOSBadge>
          ) : plan.status === 'modified' ? (
            <LifeOSBadge variant="primary">
              Modified Constraints
            </LifeOSBadge>
          ) : plan.status === 'rejected' ? (
            <LifeOSBadge variant="danger">
              Rejected (Pending Re-planning)
            </LifeOSBadge>
          ) : (
            <LifeOSBadge variant="warning" pulse>
              Awaiting User Review
            </LifeOSBadge>
          )}
        </div>
      </div>

      {/* Summary Banner */}
      <div className="p-6 sm:p-7 rounded-3xl bg-white border border-slate-200/90 shadow-soft space-y-4">
        <div className="flex items-start gap-3.5">
          <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-blue-600 to-indigo-600 text-white flex items-center justify-center flex-shrink-0 shadow-sm mt-0.5">
            <Compass className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-base sm:text-lg font-bold text-slate-800">
              Coordinated Strategy Summary
            </h2>
            <p className="text-xs sm:text-sm text-slate-600 mt-1 leading-relaxed">
              {plan.summary}
            </p>
          </div>
        </div>

        {/* Action Controls for User Approval */}
        <div className="pt-4 border-t border-slate-100 flex flex-wrap items-center justify-between gap-3">
          <div className="text-xs text-slate-500">
            {plan.status === 'approved' ? (
              <span className="text-emerald-600 font-semibold flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4" />
                Plan is active. Action Agent is processing approved steps.
              </span>
            ) : (
              <span>Review the phases, trade-offs, and evidence below before approving.</span>
            )}
          </div>

          <div className="flex items-center gap-2">
            <LifeOSButton
              onClick={() => setShowRejectModal(true)}
              variant="outline"
              size="sm"
            >
              Reject Plan
            </LifeOSButton>
            <LifeOSButton
              onClick={() => setShowModifyModal(true)}
              variant="secondary"
              size="sm"
              leftIcon={<Sliders className="w-3.5 h-3.5" />}
            >
              Modify Constraints
            </LifeOSButton>
            <LifeOSButton
              onClick={handleApprove}
              disabled={plan.status === 'approved'}
              variant="success"
              size="md"
              leftIcon={<CheckCircle2 className="w-4 h-4" />}
            >
              {plan.status === 'approved' ? 'Plan Approved' : 'Approve Plan'}
            </LifeOSButton>
          </div>
        </div>
      </div>

      {/* Sequential Plan Steps */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-base font-bold text-[#0B192C]">
            Execution Steps & Dependencies
          </h3>
          <span className="text-xs text-slate-400 font-medium">
            4 sequential phases
          </span>
        </div>

        <div className="space-y-3">
          {plan.steps.map((step, idx) => (
            <div
              key={step.id}
              className="p-5 sm:p-6 rounded-3xl bg-white border border-slate-200/90 shadow-soft flex flex-col md:flex-row md:items-center justify-between gap-4"
            >
              <div className="flex items-start gap-3.5">
                <div className="w-9 h-9 rounded-2xl bg-blue-50 text-[#1E60F2] font-bold text-xs flex items-center justify-center flex-shrink-0 border border-blue-100">
                  0{idx + 1}
                </div>
                <div>
                  <div className="flex items-center gap-2 mb-0.5">
                    <h4 className="text-sm sm:text-base font-bold text-slate-800">
                      {step.title}
                    </h4>
                    <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-md bg-slate-100 text-slate-600">
                      Phase {step.phase}
                    </span>
                  </div>
                  <p className="text-xs text-slate-500 leading-relaxed max-w-xl">
                    {step.description}
                  </p>
                  {step.dependencies && (
                    <div className="mt-1.5 text-[11px] text-amber-700 font-medium flex items-center gap-1">
                      <AlertTriangle className="w-3.5 h-3.5 text-amber-500" />
                      <span>Dependent on: {step.dependencies.join(', ')}</span>
                    </div>
                  )}
                </div>
              </div>

              <div className="flex items-center gap-5 text-xs font-medium text-slate-500 pl-12 md:pl-0 border-t md:border-t-0 pt-3 md:pt-0 border-slate-100">
                {step.estimatedCost && (
                  <div className="text-left md:text-right">
                    <span className="text-[10px] text-slate-400 uppercase block font-bold">Cost</span>
                    <span className="font-bold text-slate-700">{step.estimatedCost}</span>
                  </div>
                )}
                {step.duration && (
                  <div className="text-left md:text-right">
                    <span className="text-[10px] text-slate-400 uppercase block font-bold">Duration</span>
                    <span className="font-bold text-slate-700">{step.duration}</span>
                  </div>
                )}
                <div className="text-left md:text-right">
                  <span className="text-[10px] text-slate-400 uppercase block font-bold">Agent</span>
                  <span className="font-bold text-[#1E60F2] capitalize">{step.assignedAgent}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Trade-Off Analysis */}
      <div className="p-6 sm:p-7 rounded-3xl bg-white border border-slate-200/90 shadow-soft space-y-4">
        <h3 className="text-base font-bold text-[#0B192C]">
          Evaluated Housing Options & Trade-Offs
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {plan.tradeOffs.map((option, idx) => (
            <div
              key={idx}
              className="p-5 rounded-2xl bg-slate-50 border border-slate-200/80 flex flex-col justify-between"
            >
              <div>
                <span className="text-[10.5px] font-bold text-[#1E60F2] uppercase tracking-wider block mb-1">
                  Scenario {idx + 1}
                </span>
                <p className="text-xs text-slate-700 leading-relaxed font-medium">
                  {option}
                </p>
              </div>
              <div className="mt-4 pt-2.5 border-t border-slate-200 text-[11px] text-slate-500 flex items-center justify-between">
                <span>Budget Compliant</span>
                <span className="text-emerald-600 font-bold">✓ ₹15k Cap Met</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Risk & Mitigation Matrix */}
      <div className="p-6 sm:p-7 rounded-3xl bg-white border border-slate-200/90 shadow-soft space-y-4">
        <h3 className="text-base font-bold text-[#0B192C] flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 text-amber-500" />
          <span>Risk Assessment & Automated Contingencies</span>
        </h3>
        <div className="space-y-3">
          {risksAndMitigations.map((item, idx) => (
            <div
              key={idx}
              className="p-4 rounded-2xl bg-slate-50/70 border border-slate-200/80 flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs"
            >
              <div className="space-y-0.5">
                <div className="flex items-center gap-2">
                  <span className="font-bold text-slate-800">{item.risk}</span>
                  <span
                    className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                      item.severity === 'High'
                        ? 'bg-rose-100 text-rose-800'
                        : item.severity === 'Medium'
                        ? 'bg-amber-100 text-amber-800'
                        : 'bg-blue-100 text-blue-800'
                    }`}
                  >
                    {item.severity} Risk
                  </span>
                </div>
                <p className="text-slate-600 text-[11.5px]">{item.mitigation}</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Verification Evidence & Sources */}
      <div className="p-6 sm:p-7 rounded-3xl bg-slate-900 text-white shadow-soft space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-5 h-5 text-emerald-400" />
            <h3 className="text-base font-bold">
              Audited Facts & Verification Proofs
            </h3>
          </div>
          <span className="text-xs text-emerald-400 font-semibold">
            100% Constraints Mathematically Verified
          </span>
        </div>

        <div className="space-y-2.5">
          {plan.evidenceNotes.map((note, idx) => (
            <div
              key={idx}
              className="p-3.5 rounded-2xl bg-white/10 border border-white/10 text-xs text-slate-200 flex items-start gap-3"
            >
              <CheckCircle2 className="w-4 h-4 text-emerald-400 mt-0.5 flex-shrink-0" />
              <span>{note}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Modify Constraints Modal */}
      <LifeOSModal
        isOpen={showModifyModal}
        onClose={() => setShowModifyModal(false)}
        title="Modify Plan Constraints"
        subtitle="Planning Agent will re-calculate options based on your revised parameters."
        footer={
          <>
            <LifeOSButton
              variant="outline"
              size="sm"
              onClick={() => setShowModifyModal(false)}
            >
              Cancel
            </LifeOSButton>
            <LifeOSButton
              variant="primary"
              size="sm"
              onClick={handleModifySubmit}
            >
              Re-evaluate Plan
            </LifeOSButton>
          </>
        }
      >
        <form onSubmit={handleModifySubmit} className="space-y-4">
          <div>
            <label className="text-xs font-bold text-slate-700 block mb-1">
              Monthly Budget Cap
            </label>
            <input
              type="text"
              value={budgetCap}
              onChange={(e) => setBudgetCap(e.target.value)}
              className="w-full px-3 py-2 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#1E60F2]"
            />
          </div>
          <div>
            <label className="text-xs font-bold text-slate-700 block mb-1">
              Max Commute Time
            </label>
            <input
              type="text"
              value={maxCommute}
              onChange={(e) => setMaxCommute(e.target.value)}
              className="w-full px-3 py-2 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#1E60F2]"
            />
          </div>
        </form>
      </LifeOSModal>

      {/* Reject Modal */}
      <LifeOSModal
        isOpen={showRejectModal}
        onClose={() => setShowRejectModal(false)}
        title="Reject Plan & Request Alternatives"
        subtitle="Explain what needs to change so the Planning Agent can search different routes."
        footer={
          <>
            <LifeOSButton
              variant="outline"
              size="sm"
              onClick={() => setShowRejectModal(false)}
            >
              Cancel
            </LifeOSButton>
            <LifeOSButton
              variant="danger"
              size="sm"
              onClick={handleRejectSubmit}
            >
              Confirm Rejection
            </LifeOSButton>
          </>
        }
      >
        <form onSubmit={handleRejectSubmit} className="space-y-4">
          <textarea
            rows={3}
            required
            value={feedbackText}
            onChange={(e) => setFeedbackText(e.target.value)}
            placeholder="E.g. Prefer private hostel instead of flat sharing, or desire single room..."
            className="w-full p-3 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-[#1E60F2]"
          />
        </form>
      </LifeOSModal>
    </div>
  );
};
